package br.com.ambientinformatica.senai.universitario.entidade;
// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="cooperativas"
)
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private Endereco endereco;
     private String razaoSocial;
     private String nomeFantasia;
     private String cnpj;
     private String telefone;
     private Set<Cooperativa> cooperativas = new HashSet<Cooperativa>(0);

    public Empresa() {
    }

	
    public Empresa(Endereco endereco, String razaoSocial, String nomeFantasia, String cnpj, String telefone) {
        this.endereco = endereco;
        this.razaoSocial = razaoSocial;
        this.nomeFantasia = nomeFantasia;
        this.cnpj = cnpj;
        this.telefone = telefone;
    }
    public Empresa(Endereco endereco, String razaoSocial, String nomeFantasia, String cnpj, String telefone, Set<Cooperativa> cooperativas) {
       this.endereco = endereco;
       this.razaoSocial = razaoSocial;
       this.nomeFantasia = nomeFantasia;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.cooperativas = cooperativas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEmpresa", unique=true, nullable=false)
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="RazaoSocial", nullable=false, length=150)
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

    
    @Column(name="NomeFantasia", nullable=false, length=150)
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    
    @Column(name="CNPJ", nullable=false, length=45)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="telefone", nullable=false, length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Cooperativa> getCooperativas() {
        return this.cooperativas;
    }
    
    public void setCooperativas(Set<Cooperativa> cooperativas) {
        this.cooperativas = cooperativas;
    }




}


