package br.com.cooperativa.entidade;

// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Cursotecnico generated by hbm2java
 */
@Entity
public class CursoTecnico implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "ctecnico_seq", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "ctecnico_seq", sequenceName = "ctecnico_seq", allocationSize = 1, initialValue = 1)
	private Integer idCursoTecnico;
	private String nome;
	private String descricao;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "adesao")
	@Fetch(FetchMode.JOIN)
	private Adesao adesao;

	public CursoTecnico() {

	}

	public Adesao getAdesao() {
		return adesao;
	}

	public void setAdesao(Adesao adesao) {
		this.adesao = adesao;
	}

	public Integer getIdCursoTecnico() {
		return idCursoTecnico;
	}

	public void setIdCursoTecnico(Integer idCursoTecnico) {
		this.idCursoTecnico = idCursoTecnico;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}