package br.com.cooperativa.entidade;

// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Dependente generated by hbm2java
 */
@Entity
public class Dependente implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "dependente_seq", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "dependente_seq", sequenceName = "dependente_seq", allocationSize = 1, initialValue = 1)
	private Integer idDependente;
	private Date dataNascimento;
	private String situacao;
	private String nome;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "adesao")
	@Fetch(FetchMode.JOIN)
	private Adesao adesao;

	public Dependente() {
	}

	public Adesao getAdesao() {
		return adesao;
	}

	public void setAdesao(Adesao adesao) {
		this.adesao = adesao;
	}

	public Integer getIdDependente() {
		return idDependente;
	}

	public void setIdDependente(Integer idDependente) {
		this.idDependente = idDependente;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public String getSituacao() {
		return situacao;
	}

	public void setSituacao(String situacao) {
		this.situacao = situacao;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	// /* Overrride */
	// @Override
	// public int hashCode() {
	// final int prime = 31;
	// int result = 1;
	// result = prime * result
	// + ((idDependente == null) ? 0 : idDependente.hashCode());
	// return result;
	// }
	//
	// @Override
	// public boolean equals(Object obj) {
	// if (this == obj)
	// return true;
	// if (obj == null)
	// return false;
	// if (getClass() != obj.getClass())
	// return false;
	// Dependente other = (Dependente) obj;
	// if (idDependente == null) {
	// if (other.idDependente != null)
	// return false;
	// } else if (!idDependente.equals(other.idDependente))
	// return false;
	// return true;
	// }
	//
	@Override
	public String toString() {
		return this.nome;
	}
	//
}