package br.com.cooperativa.entidade;
// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name="sequence"
    ,catalog="cooperativas"
)
public class Sequence  implements java.io.Serializable {


     private String seqName;
     private BigDecimal seqCount;

    public Sequence() {
    }

	
    public Sequence(String seqName) {
        this.seqName = seqName;
    }
    public Sequence(String seqName, BigDecimal seqCount) {
       this.seqName = seqName;
       this.seqCount = seqCount;
    }
   
     @Id 

    
    @Column(name="SEQ_NAME", unique=true, nullable=false, length=50)
    public String getSeqName() {
        return this.seqName;
    }
    
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    
    @Column(name="SEQ_COUNT", precision=38, scale=0)
    public BigDecimal getSeqCount() {
        return this.seqCount;
    }
    
    public void setSeqCount(BigDecimal seqCount) {
        this.seqCount = seqCount;
    }




}


