package br.com.cooperativa.entidade;

// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuariosistema generated by hbm2java
 */
@Entity
public class Usuariosistema implements java.io.Serializable {

	private Integer idUsuarioSistema;
	private Cooperado cooperado;
	private String senha;
	private String tipo;

	// private Set<Cooperado> cooperados = new HashSet<Cooperado>(0);

	public Usuariosistema() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUsuarioSistema", unique = true, nullable = false)
	public Integer getIdUsuarioSistema() {
		return this.idUsuarioSistema;
	}

	public void setIdUsuarioSistema(Integer idUsuarioSistema) {
		this.idUsuarioSistema = idUsuarioSistema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCoopr", nullable = false)
	public Cooperado getCooperado() {
		return this.cooperado;
	}

	public void setCooperado(Cooperado cooperado) {
		this.cooperado = cooperado;
	}

	@Column(name = "senha", nullable = false, length = 45)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "tipo", nullable = false, length = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
