package br.com.ambientinformatica.senai.universitario.entidade;

// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;

import br.com.ambientinformatica.senai.universitario.util.WebServiceCep;

/**
 * Endereco generated by hbm2java
 */
@Entity
public class Endereco {

	@Id
	@GeneratedValue(generator = "endereco_seq", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "endereco_seq", sequenceName = "endereco_seq", allocationSize = 1, initialValue = 1)
	private Integer idendereco;
	@ManyToOne(fetch = FetchType.EAGER)
	private Cidade cidade;
	private String logradouro;
	private String bairro;
	private String numero;
	private String complemento;
	private String cep;

	public Endereco() {

	}

	public Integer getIdendereco() {
		return idendereco;
	}

	public void setIdendereco(Integer idendereco) {
		this.idendereco = idendereco;
	}

	public Cidade getCidade() {
		return cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

}