package br.com.ambientinformatica.senai.universitario.entidade;

// Generated 21/11/2013 13:33:34 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiacao generated by hbm2java
 */
@Entity
public class Filiacao implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "filiacao_seq", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "filiacao_seq", sequenceName = "filiacao_seq", allocationSize = 1, initialValue = 1)
	private Integer idFiliacao;
	private String nomePai;
	private String nomeMae;

	public Integer getIdFiliacao() {
		return idFiliacao;
	}

	public void setIdFiliacao(Integer idFiliacao) {
		this.idFiliacao = idFiliacao;
	}

	public String getNomePai() {
		return nomePai;
	}

	public void setNomePai(String nomePai) {
		this.nomePai = nomePai;
	}

	public String getNomeMae() {
		return nomeMae;
	}

	public void setNomeMae(String nomeMae) {
		this.nomeMae = nomeMae;
	}

}